#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : html5lib
Version  : 0.9999999
Release  : 8
URL      : http://pypi.debian.net/html5lib/html5lib-0.9999999.tar.gz
Source0  : http://pypi.debian.net/html5lib/html5lib-0.9999999.tar.gz
Summary  : HTML parser based on the WHATWG HTML specification
Group    : Development/Tools
License  : MIT
Requires: html5lib-python3
Requires: html5lib-python
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
========

%package python
Summary: python components for the html5lib package.
Group: Default
Requires: html5lib-python3

%description python
python components for the html5lib package.


%package python3
Summary: python3 components for the html5lib package.
Group: Default
Requires: python3-core

%description python3
python3 components for the html5lib package.


%prep
%setup -q -n html5lib-0.9999999

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507154975
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
